name: Build Spigot

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    name: Build Spigot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build and Upload
        run: bash index.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
